on:
  push:
    branches: ['stable']

name: Sync submodules to main repo

jobs:
  sync:
    name: Sync stable branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: '21sbecker/assembler-crates'
          ref: 'stable'
          token: ${{ secrets.GT_PAT }}
          fetch-depth: '0'
          submodules: true
      - name: Update submodule and push
        run: |
          git submodule update --remote -- ${{ gitea.event.repository.name }}
          git config --local user.email "21sbecker@cloak.mafiasi.de"
          git config --local user.name "Gitea Action"
          git add -A
          git commit -m "update from ${{ gitea.event.repository.name }}"
          git push

